application:
  subdomain: netronome
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://netronome:7575/
services:
  netronome:
    # upstream: ghcr.io/autobrr/netronome:v0.14.0
    image: ghcr.1ms.run/autobrr/netronome:v0.14.0
    user: root
    binds:
      - /lzcapp/var/data:/data
    cpu_shares: 512
    mem_limit: 512M
