lzc-sdk-version: "0.1"
name: Netronome
package: cloud.lazycat.app.netronome
version: 0.8.0
min_os_version: 1.3.8
description: "Netronome is a modern network speed testing and monitoring tool built with Go and React"
license: MIT
homepage: https://github.com/autobrr/netronome
author: autobrr

application:
  subdomain: netronome
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://netronome:7575/

services:
  netronome:
    # ghcr.io/autobrr/netronome:develop
    image: registry.lazycat.cloud/czyt/autobrr/netronome:3cfb73b0f2055a7e
    user: root
    binds:
      - /lzcapp/var/data:/data
    cpu_shares: 512
    mem_limit: 512M
    restart: unless-stopped

locales:
  en:
    name: "Netronome"
    description: "Netronome is a modern network speed testing and monitoring tool built with Go and React"
  zh:
    name: "Netronome"
    description: "Netronome 是一个基于 Go 和 React 构建的现代化网络速度测试和监控工具"
