package: cloud.lazycat.app.netronome
version: 0.14.1
name: Netronome
description: "Netronome is a modern network speed testing and monitoring tool built with Go and React"
license: MIT
homepage: https://github.com/autobrr/netronome
author: autobrr
min_os_version: 1.5.0
locales:
  en:
    name: "Netronome"
    description: "Netronome is a modern network speed testing and monitoring tool built with Go and React"
  zh:
    name: "Netronome"
    description: "Netronome 是一个基于 Go 和 React 构建的现代化网络速度测试和监控工具"
